### ISSUE TITLE
[BUG REPORT]

### ISSUE THREAD

**Issue by withabdul** [TeamUltroid/Ultroid#108]
**Describe the bug**
As i see in [package.json](https://github.com/TeamUltroid/Ultroid/blob/main/package.json) the version of `typegram` is outdated, and because of that, the deployment can't working.

**To Reproduce**
Update `typegram` version to 3.4.0 (based on [npmjs](https://www.npmjs.com/package/typegram) )

**Expected behavior**
Deployment now will working again

**Versions (please complete the following information):**
 - Ultroid Version: 0.0.8
 - pyUltroid Version: 2021.6.18.1
(these can be found in the first line of your logs.)

**Client Used (please complete the following information):**
 - Device: Phone
 - Client: Telegram Official, Nekogram X

**Additional context**
None

**Comment by New-dev0** [comment]
Upgrading typegram to 3.4.0, still didn't fixed this issue 🤒

**Comment by withabdul** [comment]
I'll try to debug it, because mine is working fine.

Pada tanggal Kam, 1 Jul 2021 20.38, Devesh Pal ***@***.***>
menulis:

**Comment by New-dev0** [comment]
This Has been Fixed :)
Thanks for Opening Issue !
