### ISSUE TITLE
Help us Translate Ultroid in other languages.

### ISSUE THREAD

**Issue by New-dev0** [TeamUltroid/Ultroid#175]
Ultroid has Multi Language Support.
We are looking for some help, to complete translation work.

Your language strings must be added to the folder [`strings/strings/`](https://github.com/TeamUltroid/Ultroid/tree/dev/strings/strings).

You can download [English strings](https://github.com/TeamUltroid/Ultroid/blob/dev/strings/strings/en.yml), translate it to your desired language and put it to the path in format `languagecode.yml`.
or you can fix any mistakes done in language strings...

Note : Some Strings are still present in source, which needs to be seperated out for translation purpose. Doing that too, will be appreciated.

After doing your changes, you can create a Pull Request and mention this Issue in that.

**Comment by arsheelsheikh** [comment]
can I work on this issue for translating `strings` into `Urdu` language

**Comment by TechiError** [comment]
> can I work on this issue for translating `strings` into `Urdu` language

Yeah you can.
And thanks if you want to contribute :P .

**Comment by davidclarance** [comment]
Would it be okay if I took Kiswahili?

**Comment by 1Danish-00** [comment]
> Would it be okay if I took Kiswahili?

yup.

**Comment by rez4ie** [comment]
Persian(fa) is an RTL lang, it really messes things up I'd rather it to be removed :)

**Comment by amitkr-codes** [comment]
@rez4ie How does it mess?

**Comment by New-dev0** [comment]
> @rez4ie How does it mess?

strings, format, order

**Comment by amitkr-codes** [comment]
@rez4ie Make corrections and make pr

**Comment by New-dev0** [comment]
> @New-dev0 Make corrections and make pr

I dont know persian 🤷‍♂️🤕

**Comment by amitkr-codes** [comment]
@New-dev0 Wrong tag
Blame @githubbot

**Comment by luisAzcuaga** [comment]
Can I help translating to spanish? 🇲🇽

**Comment by 1Danish-00** [comment]
> Can I help translating to spanish? 🇲🇽

Obviously

**Comment by sonzaiekkusu** [comment]
maybe indonesian

**Comment by TechiError** [comment]
> maybe indonesian

You can translate to Indonesian in the given format and give a pull request to ultroid. :)
Or you may find someone who can translate to indonesian.

**Comment by TechiError** [comment]
Issue has been moved to :- https://github.com/TeamUltroid/Ultroid/discussions/205

**Comment by XstepAhead** [comment]
> > maybe indonesian
> 
> You can translate to Indonesian in the given format and give a pull request to ultroid. :) Or you may find someone who can translate to indonesian.

im from indonesian maybe i will translate and give a pull request

**Comment by Achu2234** [comment]
I can help u in translation of jp

**Comment by iAkashPattnaik** [comment]
@Achu2234 how about translating into klingon

**Comment by Achu2234** [comment]
@BLUE-DEVIL1134 I am not a alien

**Comment by iAkashPattnaik** [comment]
then die

**Comment by Achu2234** [comment]
@BLUE-DEVIL1134 u can translate intoto klingon

**Comment by iAkashPattnaik** [comment]
me never watched star wars, saw it in the big bang theory

**Comment by Achu2234** [comment]
oh

**Comment by New-dev0** [comment]
> I can help u in translation of jp

Ya, you can
Please also mention full form of Language too

**Comment by Achu2234** [comment]
japanese

**Comment by Achu2234** [comment]
https://github.com/TeamUltroid/Ultroid/pull/228
@New-dev0

**Comment by Achu2234** [comment]
@New-dev0 sir do u merge to dev

**Comment by New-dev0** [comment]
✨ Want to Inform

• Some New strings are added to dev branch, Missing count can be found [Here](https://github.com/TeamUltroid/Ultroid/tree/dev/strings)
• You can find listed missing strings [Here](https://github.com/TeamUltroid/Ultroid/blob/dev/strings/remaining.csv). [Created for easy sort out]

• It will be great for us, if they can be translated before the next  update(year).
• You can submit your changes to `beta` branch, so that a proper commit history can be maintained, and translated strings and related Updates can be push together to main.

Happy Translating.. \ (^o^) /

**Comment by Achu2234** [comment]
you mean want to translate new string in jp also

**Comment by New-dev0** [comment]
> you mean want to translate new string in jp also

Yes, Japanese is also missing 18 new strings
https://github.com/TeamUltroid/Ultroid/tree/dev/strings

**Comment by Achu2234** [comment]
> > you mean want to translate new string in jp also
> 
> Yes, Japanese is also missing 18 new strings https://github.com/TeamUltroid/Ultroid/tree/dev/strings

ok

**Comment by Mpk2022** [comment]
Hello, I have finished the translation. how can it work？
I tried putting the translated yml file into the folder, but it doesn't seem to work

**Comment by New-dev0** [comment]
> Hello, I have finished the translation. how can it work？ I tried putting the translated yml file into the folder, but it doesn't seem to work

Are you using your fork as your userbot? 
if no, then create a pull request to this repository.

**Comment by Achu2234** [comment]
@New-dev0 Any Remaing Translation in jp string can u tell me

**Comment by New-dev0** [comment]
@Achu2234 No, In jp there are no remaining translation for now! 
Thanks to you

**Comment by New-dev0** [comment]
Moving this issue to Discussion https://github.com/TeamUltroid/Ultroid/discussions/205
