### ISSUE TITLE
[Suggestion] Add warning on the readme

### ISSUE THREAD

**Issue by TsunayoshiSawada** [TeamUltroid/Ultroid#223]
### Contact Details

@Sawada

### What happened?

Add some warning cause users come around asking if the bot is safe/unsafe, what can happen on use and abuse of a bot. 
This type of stuff should at least be linked on top the readme somewhere in visibility 

Thanks. 

PS: Please also add a "suggestions" section on the issues section 

### Version

0.0.8 (or later)

### Relevant logs output

```shell
N/A
```

### Acknowledgement

- [x] I have followed all of the above steps.

**Comment by 1Danish-00** [comment]
> ### Contact Details
> @sawada
> 
> ### What happened?
> Add some warning cause users come around asking if the bot is safe/unsafe, what can happen on use and abuse of a bot. This type of stuff should at least be linked on top the readme somewhere in visibility
> 
> Thanks.
> 
> PS: Please also add a "suggestions" section on the issues section
> 
> ### Version
> 0.0.8 (or later)
> 
> ### Relevant logs output
> ```shell
> N/A
> ```
> 
> ### Acknowledgement
> * [x]  I have followed all of the above steps.

- Ultroid is not among those spam Userbot. Telegram ban accounts if you go against their term of services. Ultroid officially don't have any abuse/animation/inviteall plugin.
- And While SignUp they are asked to agree Telegram Tos which can't be declined.

Hence I'm closing this issue.
