### ISSUE TITLE
Startup file is giving error

### ISSUE THREAD

**Issue by MrSp4rX** [TeamUltroid/Ultroid#259]
### Contact Details

@MrSp4rX

### What happened?

first of all i read your manual and download whole code and did the setup of requirements file and .env file and when i was about to run startup file in location Ultroid\resources\startup\startup.sh its started giving me import errors. I solved some of them with pip and some sites but this one isnt being solved by me and i dont know why. error is:
ModuleNotFoundError: No module named 'safety.tools'
after this is installed safety module via pip install safety but still its giving me error and i tried to import module directly like import safety then its not giving any error. i think its .tools section is removed and i tried to find but i didnt get the older version that you guys are using. Plz help.

### Version

0.3

### Hosted On

Didn't Deployed Yet

### Acknowledgement

- [x] #261

**Comment by xditya** [comment]
Hello @MrSp4rX, thanks for opening an issue.
It look like you haven't installed all the requirements. Please do a `pip install -r requirements.txt && pip install -r res*/st*/opt*` and run the bot again by `bash startup`
