### ISSUE TITLE
[ERROR REPORT]

### ISSUE THREAD

**Issue by Pranay5463** [TeamUltroid/Ultroid#274]
### Contact Details

@loyaltyoveroyalty

### I got error saying app.json file is missing

**PLZZ See to this issue**

**_Contact me if you need to tell me privately anything
[@loyaltyoveroyalty](https://t.me/loyaltyoveroyalty) on telegram_**

### Version

0.3

### Hosted On

Heroku

### Acknowledgement

- [X] I have followed all of the above steps.

**Comment by Pranay5463** [comment]
### Here is the screenshot provided 



[Screenshot_20220221-071044](https://user-images.githubusercontent.com/86947553/154875450-a398f6ec-4ec0-4aa7-8680-6a1d020d403f.png)

**Comment by New-dev0** [comment]
This issue has been fixed. 
You can use https://deploy.ultroid.tech for heroku deploy again.
