### ISSUE TITLE
Complaint

### ISSUE THREAD

**Issue by XRoiDX** [TeamUltroid/Ultroid#322]
### What happened?

My Telegram 2 Number Has Be Banned This User Bot Deployed

### Version

0.3

### Hosted On

Heroku

### Relevant logs output

```shell
Banned My Numbers
```

### Acknowledgement

- [x] I have followed all of the above steps.

**Comment by iAkashPattnaik** [comment]
There is no relevance that Ultroid is the reason for he ban of your account, thousands of people use Ultroid around the globe, since a major number of people haven't faced this problem, it's a YOU thing.

~ by Akash Pattnaik.
