### ISSUE TITLE
[BUG REPORT]

### ISSUE THREAD

**Issue by xtsea** [TeamUltroid/Ultroid#330]
### Contact Details

@UltroidASupport

### What happened?

What happened Grup Ultroid banned ?

see

![Screenshot_2022-07-03_002138](https://user-images.githubusercontent.com/90479255/177010279-1e54e662-f48f-4dc9-acd2-e3d4739e8871.jpg)

### Version

0.1

### Hosted On

Other

### Acknowledgement

- [X] I have followed all of the above steps.

**Comment by xditya** [comment]
https://t.me/TheUltroid/84
