### ISSUE TITLE
[Heroku Deploy] akinator.py

### ISSUE THREAD

**Issue by rahulkhatri137** [TeamUltroid/Ultroid#355]
ERROR: Could not find a version that satisfies the requirement akinator.py

**Comment by sony-z1** [comment]
me too:

ERROR: Ignored the following versions that require a different python version: 2022.1.1 Requires-Python >3.6, <3.10; 2022.1.1.1 Requires-Python >3.6, <3.10
       ERROR: Could not find a version that satisfies the requirement akinator.py (from versions: none)
       ERROR: No matching distribution found for akinator.py
 !     Push rejected, failed to compile Python app.
 !     Push failed

**Comment by rahulkhatri137** [comment]
**pyUltroid/functions/ytdl.py:190: SyntaxWarning: "is not" with a literal. Did you mean "!="?
if vid["vcodec"] is not "none":**
