### ISSUE TITLE
instagram [BUG REPORT]

### ISSUE THREAD

**Issue by titu3e** [TeamUltroid/Ultroid#374]
### Contact Details

@its_kayden

### What happened?

A bug happened! instagram plugin is not working :
it just shows error or sometimes it doesnt reply anything and becomes un-responsive 

### Version

> 0.7

### Hosted On

Vps

### Relevant logs output

```shell
'int' object has no attribute 'encode'
```

### Acknowledgement

- [x] I have followed all of the above steps.

**Comment by sppidy** [comment]
Instagram plugin is no longer available
