### ISSUE TITLE
[BUG REPORT]

### ISSUE THREAD

**Issue by ghost** [TeamUltroid/Ultroid#384]
### Contact Details

cat@cat.com

### What happened?

Its not a bug its a simple feature request 

can you add this to docker-compose.yml
`container_name: ultroid`

its easier to manager container that way using names 

### Version

> 0.7

### Hosted On

Other

### Relevant logs output

```shell
NO error
```

### Acknowledgement

- [X] I have followed all of the above steps.

**Comment by New-dev0** [comment]
Create a PR committing your requested changes..
