### ISSUE TITLE
[REQUEST] Docker support?

### ISSUE THREAD

**Issue by Velosofy** [TeamUltroid/Ultroid#391]
### Contact Details

@velosofyy

### What happened?

Is there a chance for a docker support?
A simple Dockerfile would suffice I feel like.

### Version

> 0.7

### Hosted On

Didn't Deployed Yet

### Acknowledgement

- [X] I have followed all of the above steps.

**Comment by xditya** [comment]
For anyone here, we have a Dockerfile, and you can run it using: 
> `docker build -t ultroid ./Dockerfile`
> `docker run ultroid`

**Comment by Velosofy** [comment]
Yeah sorry I went full-on-blind mode. I didn't realize there is a Dockerfile, didn't mentioned in the README
