### ISSUE TITLE
[BUG REPORT] Refused to start

### ISSUE THREAD

**Issue by Velosofy** [TeamUltroid/Ultroid#392]
### Contact Details

@velosofyy

### What happened?

Ultroid refused to start
Hosted on a docker container using Dockerfile

I already make sure that I fill the .env properly

### Version

> 0.7

### Hosted On

Vps

### Relevant logs output

```shell
┏┳┓╋┏┓╋╋╋╋┏┓┏┓
            ┃┃┣┓┃┗┳┳┳━╋╋┛┃
            ┃┃┃┗┫┏┫┏┫╋┃┃╋┃
            ┗━┻━┻━┻┛┗━┻┻━┛

      Visit @TheUltroid for updates!!


11/29/2022, 21:11:32 | pyUltLogs [INFO] :
                    -----------------------------------
                            Starting Deployment
                    -----------------------------------

11/29/2022, 21:11:32 | pyUltLogs [INFO] : Python version - 3.10.2
11/29/2022, 21:11:32 | pyUltLogs [INFO] : py-Ultroid Version - 2022.08.30
11/29/2022, 21:11:32 | pyUltLogs [INFO] : Telethon Version - 1.25.1 [Layer: 146]
11/29/2022, 21:11:32 | pyUltLogs [INFO] : Ultroid Version - 0.7.1 [github actions]
11/29/2022, 21:11:32 | pyUltLogs [INFO] : Using local file as database.
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
11/29/2022, 21:11:39 | pyUltLogs [CRITICAL] : No DB requirement fullfilled!
Please install redis, mongo or sql dependencies...
Till then using local file as database.
```

### Acknowledgement

- [X] I have followed all of the above steps.

**Comment by xditya** [comment]
please make sure to install the requirements via `pip install -r requirements.txt && pip install -r resources/startup/opt*`. 
if done already, just `pip install -q redis hiredis` (for redis) or `pip install -q pymongo[srv]` (for mongodb) or `pip install -q psycopg2-binary` (for SQL), whichever is preferred.

**Comment by Velosofy** [comment]
After a lot of troubleshooting, the problem is because the Dockerfile doesnt copy the config file

**Comment by xditya** [comment]
Hope it's fixed now. Closing.
