### ISSUE TITLE
[BUG REPORT]

### ISSUE THREAD

**Issue by qiniso45** [TeamUltroid/Ultroid#409]
### Contact Details

@Dead_insude_m17

### What happened?

A bug happened!...it wants username when i am trying to clone

### Version

0.5

### Hosted On

Vps

### Acknowledgement

- [ ] I have followed all of the above steps.

**Comment by xditya** [comment]
Provide the logs.

**Comment by TechiError** [comment]
Update to the latest version and check if the bug exists, if it exists, report again

**Comment by qiniso45** [comment]
fixed
________________________________
