### ISSUE TITLE
[BUG REPORT]

### ISSUE THREAD

**Issue by SobhanCU** [TeamUltroid/Ultroid#411]
### Contact Details

sobhancu

### What happened?

A bug happened!
When the **edit takes** is turned on and you're a sudo of someone's userbot and they set a handler for sudo users, you send a message and then edit it to a command, but the command is written with the handler of their userbot (the main handler, not sudo handler), and the userbot will take it as the command and run it!

### Version

> 0.7

### Hosted On

Vps

### Relevant logs output

```shell
No log,
```

### Acknowledgement

- [X] I have followed all of the above steps.

**Comment by xditya** [comment]
That is exactly why it's called "edit takes", it takes edits for a command.

However you edit, using SUDO or manually, the update is received as edited by the sender, and not someone else.
