### ISSUE TITLE
HEROKU ISSUE

### ISSUE THREAD

**Issue by alportblu** [TeamUltroid/Ultroid#443]
### What happened?

A bug happened!

![Screenshot from 2024-03-31 14-33-23](https://github.com/TeamUltroid/Ultroid/assets/59105422/9f59236f-e3ac-4704-8b27-27e117da47d9)

Thank you,

### Version

> 0.7

### Hosted On

Heroku

### Acknowledgement

- [X] I have followed all of the above steps.

**Comment by xditya** [comment]
Known issue, there is nothing we can do. Consider hosting on a VPS.
Closing.
