### ISSUE TITLE
🚨 Potential Improper Access Control

### ISSUE THREAD

**Issue by huntr-helper** [TeamUltroid/Ultroid#66]
👋 Hello, @1Danish-00, @buddhhu, @xditya - a potential high severity Improper Access Control vulnerability in your repository has been disclosed to us.

#### Next Steps

1️⃣  Visit **https://huntr.dev/bounties/1-other-TeamUltroid/Ultroid** for more advisory information.

2️⃣  **[Sign-up](https://huntr.dev/)** to validate or speak to the researcher for more assistance.

3️⃣ Propose a patch or outsource it to our community - whoever fixes it gets paid.

---

#### Confused or need more help?

- Join us on our **[Discord](https://huntr.dev/discord)** and a member of our team will be happy to help! 🤗

- Speak to a member of our team: @JamieSlome

---

*This issue was automatically generated by [huntr.dev](https://huntr.dev) - a bug bounty board for securing open source code.*

**Comment by amitkr-codes** [comment]
Did anyone connect our organization there? Or are you some random shit?

**Comment by xditya** [comment]
Bots bots bots 🙄😐

**Comment by ProgrammingError** [comment]
> 👋 Hello, @1Danish-00, @buddhhu, @xditya - a potential high severity Improper Access Control vulnerability in your repository has been disclosed to us.
> 
> #### Next Steps
> 1️⃣ Visit **https://huntr.dev/bounties/1-other-TeamUltroid/Ultroid** for more advisory information.
> 
> 2️⃣ **[Sign-up](https://huntr.dev/)** to validate or speak to the researcher for more assistance.
> 
> 3️⃣ Propose a patch or outsource it to our community - whoever fixes it gets paid.
> 
> #### Confused or need more help?
> * Join us on our **[Discord](https://huntr.dev/discord)** and a member of our team will be happy to help! 🤗
> * Speak to a member of our team: @JamieSlome
> 
> _This issue was automatically generated by [huntr.dev](https://huntr.dev) - a bug bounty board for securing open source code._

Nice Attempt to scam people and devs !

**Comment by the-blank-x** [comment]
~~https://github.com/Azure/ms-rest-nodeauth/pull/117~~
I assumed the link would be private because it's a security vulnerability but I checked and it's marked as invalid, sorry

**Comment by sppidy** [comment]
> 👋 Hello, @1Danish-00, @buddhhu, @xditya - a potential high severity Improper Access Control vulnerability in your repository has been disclosed to us.
> 
> #### Next Steps
> 1️⃣ Visit **https://huntr.dev/bounties/1-other-TeamUltroid/Ultroid** for more advisory information.
> 
> 2️⃣ **[Sign-up](https://huntr.dev/)** to validate or speak to the researcher for more assistance.
> 
> 3️⃣ Propose a patch or outsource it to our community - whoever fixes it gets paid.
> 
> #### Confused or need more help?
> * Join us on our **[Discord](https://huntr.dev/discord)** and a member of our team will be happy to help! 🤗
> * Speak to a member of our team: @JamieSlome
> 
> _This issue was automatically generated by [huntr.dev](https://huntr.dev) - a bug bounty board for securing open source code._

Wow Nice try to Scam.

**Comment by hellboi-atul** [comment]
Nice scam, you all don't even know who the owners are..

**Comment by BLUE-DEVIL1134** [comment]
> Nice scam, you all don't even know who the owners are..
Well, i dont know what Ultroid is...

**Comment by hellboi-atul** [comment]
Then y receiving mails

**Comment by BLUE-DEVIL1134** [comment]
Cause Some Gamdu added me to repo.

**Comment by hellboi-atul** [comment]
🤦🏻

**Comment by sppidy** [comment]
We Will Be Fixing this issue soon

**Comment by novik8989** [comment]
Hi @sppidy, 

Thanks for the confirmation. So I assume this advisory is valid?

**Comment by sppidy** [comment]
We Have Fixed This on Dev Branch We will be Pushing to Main brach As Soon as Possible

https://github.com/TeamUltroid/Ultroid/commit/bf55cfbce4c7670af4af85553e40bbb6a175920d

**Comment by huntr-helper** [comment]
📦 A patch has been submitted for this report. 🔗 Check the patch (https://github.com/TeamUltroid/Ultroid/compare/HEAD...sppidy:dev) or visit the advisory page (https://huntr.dev/bounties/1-other-TeamUltroid/Ultroid) for more information.

**Comment by huntr-helper** [comment]
📦 A patch has been submitted for this report. 🔗 Check the patch (https://github.com/TeamUltroid/Ultroid/compare/HEAD...sppidy:dev) or visit the advisory page (https://huntr.dev/bounties/1-other-TeamUltroid/Ultroid) for more information.

**Comment by sppidy** [comment]
> Hi @sppidy, 
> 
> Thanks for the confirmation. So I assume this advisory is valid?

Yes.

**Comment by JamieSlome** [comment]
@sppidy - I can see this was marked as invalid, shall I go ahead and update it to valid?

**Comment by sppidy** [comment]
@novik8989 We Have Fixed the Issue in dev branch We Will be merging this to main branch ASAP

**Comment by sppidy** [comment]
> @sppidy - I can see this was marked as invalid, shall I go ahead and update it to valid?

Yeah Sure

**Comment by huntr-helper** [comment]
📦 A patch has been submitted for this report. 🔗 Check the patch (https://github.com/TeamUltroid/Ultroid/compare/HEAD...sppidy:dev) or visit the advisory page (https://huntr.dev/bounties/1-other-TeamUltroid/Ultroid) for more information.

**Comment by JamieSlome** [comment]
@sppidy - if @xditya now confirms the patch commit SHA for the fix on the advisory page, and selects you as the fixer, you will get the bounty for the fix, just a heads up!

Cheers 🎉

**Comment by huntr-helper** [comment]
📦 A patch has been submitted for this report. 🔗 Check the patch (https://github.com/TeamUltroid/Ultroid/compare/HEAD...sppidy:dev) or visit the advisory page (https://huntr.dev/bounties/1-other-TeamUltroid/Ultroid) for more information.

**Comment by buddhhu** [comment]
Arey bencho kya gand mara rhe ho ye issue k piche
