### ISSUE TITLE
Update error 

### ISSUE THREAD

**Issue by dinethultroid** [TeamUltroid/Ultroid#91]
Update error .plz solve this

**Comment by xditya** [comment]
Please elaborate the "error" and provide the complete Traceback so that we can look into it.

**Comment by New-dev0** [comment]
@dinethultroid Dinethultroid

**Comment by New-dev0** [comment]
It will be better to forward the logs to [@ultroidsupport](https://t.me/ultroidsupport) and continue the conversation there.
